### ISSUE TITLE
`exec-env` does not work when encrypted file is in a parent directory

### ISSUE THREAD

**Issue by ScottGuymer** [getsops/sops#1368]
I have a folder structure like

```
my-app/
├─ subfolder/
│  ├─ script.sh
├─ secrets.enc.yaml
```

from `my-app` I can run 

```
sops secrets.enc.yaml
sops -d secrets.enc.yaml
sops exe-env secrets.enc.yaml
```

all work correctly. But, if I change directory into `subfolder` then

```
sops ../secrets.enc.yaml
sops -d ../secrets.enc.yaml
```

work as expected.  However,

```
sops exe-env ../secrets.enc.yaml
```

gives an error like

```
sops exe-env ../secrets.enc.yaml
error: missing file to decrypt
```

I can't seem to see a reason why `exec-env` has a different behaviour and does not work as the other commands do.

**Comment by felixfontein** [comment]
I cannot reproduce this. First, none of the `exec-env` commands you showed actually work:
1. It's `exec-env`, not `exe-env` (I guess that typo happened when you wrote this post and it's not actually what you ran);
2. `exec-env` expects two positional parameters, you provided one (the file to decrypt).

If I run `sops exec-env ../x.yml /bin/bash` I end up in a shell where the values in `../x.yml` are available. Same for `sops exec-env ../x.yml export`. But if I run `sops exec-env ../x.yml` or `sops exec-env ../x.yml /bin/bash -c export` or something else where there are not exactly two positional arguments, I get the message you mentioned (`error: missing file to decrypt`).

So my guess is that you ran something with not exactly two positional arguments to `exec-env`.

**Comment by ScottGuymer** [comment]
Apologies, it seems I was being a total moron when I was testing this out..

What I was trying to do was make this work from a package.json...

And I think I got my wires totally crossed when I dropped out of that to a shell when it did not work correctly the first time.

In the cold light of day, and your comments I see the issue.

here is what I had in my package.json

```
{
  ...
  "scripts": {
    "dev": "sops exec-env ../secrets.dev.enc.yaml concurrently \"yarn start\" \"yarn start-backend\"",
  },
  ...
}

```

Which yielded the error above...

But adding in some `'` seems to do the trick and make it work.

```
{
  ...
  "scripts": {
    "dev": "sops exec-env ../secrets.dev.enc.yaml 'concurrently \"yarn start\" \"yarn start-backend\"'",
  },
  ...
}

```

(I dont think the error message itself helped out either 😆)

**Comment by felixfontein** [comment]
> (I dont think the error message itself helped out either 😆)

I fully agree! :)

**Comment by jscheid** [comment]
Hey, thanks for SOPS, it's a great tool. The fact that the command has to be a single argument strikes me as questionable design though for several reasons:

- It's counter-intuitive, as evidenced by this ticket. Also, the following all work as expected (skipping over `--` here for clarity):
  - `env VAR=1 cat foo`
  - `sudo cat foo`
  - `ssh host cat foo`
  - `aws-vault exec cat foo`
  - Many more examples (nohup, time, stdbuf, nice, watch, timeout, strace, perf, valgrind, chroot, etc.etc.)
- It means there is a shell of some kind involved. That means needless overhead for many use cases (even if it's only a few ms/ns) but more importantly, it introduces complexity because now I have to wonder which shell exactly is invoked, with which arguments. It's presumably `$SHELL` (via `system()`) but I shouldn't have to ask myself that question in the first place. Or it might be custom unquoting code, in which case I couldn't be sure it's POSIX compliant. I could check the code to find out but again, I shouldn't have to.
  It gives rise to all kinds of questions, for example, does `sop exec-env --same-process filename myexecutable` really replace the current process with `myexecutable`, or does it replace it with a shell which then executes `myexecutable` in a child process? Should I be running `sop exec-env --same-process filename 'exec myexecutable'` instead?
- But the biggest problem is that it needlessly forces users to make sure they quote arguments correctly, which is problematic especially for a tool in the security space, for the same reasons that [one should not call `system()`](https://wiki.sei.cmu.edu/confluence/spaces/c/pages/87152177/ENV33-C.+Do+not+call+system). And beyond that it's also simply inconvenient because quoting can be quite a bit of work to get right.

I'd suggest changing the CLI here so that all arguments after the filename are used as-is for exec or spawn, without any shell or unquoting. If people wish to use the env in a one-liner, they would still be able to do so using e.g. `sop exec-env filename sh -c 'echo $MY_SECRET'`.

**Comment by jscheid** [comment]
As an aside, I find it hard to come up with examples for when you would _not_ want to replace the `sops` process, i.e. why `--same-process` isn't the default (or why the flag exists at all.) I might be missing something?

**Comment by felixfontein** [comment]
Please don't start new discussions in closed issues. A better place would be for example #1469.
