### ISSUE TITLE
README.rst is not correctly rendered

### ISSUE THREAD

**Issue by edigaryev** [getsops/sops#1411]
Screenshot:

<img width="907" alt="Screenshot 2024-01-13 at 01 20 25" src="https://github.com/getsops/sops/assets/85709/b92485b6-6376-4faf-bc9b-005d2ccc847e">

**Comment by tidux** [comment]
I think imgur is part of the problem.  "Direct file links" aren't anymore if it detects certain user agents, including all mobile browsers.  Just put the gif in the repo.

**Comment by felixfontein** [comment]
Interesting, this must have changed recently. A few days ago I was still able to see the rendered version.

**Comment by chrisgilmerproj** [comment]
I have opened a github ticket about this because I wasn't sure what was going on and I couldn't even get to the issues tab for this repo. I think they might try to optimize to fix this issue. However, reducing the size of the file would be a big help. For different sections you could put them in a `docs/` directory with links from the original file.

Here's the error as I'm seeing it now:

<img width="911" alt="Screen Shot 2024-01-12 at 2 07 35 PM" src="https://github.com/getsops/sops/assets/219296/b2a4d20e-a0cd-46d1-a45e-bd1f5ff99436">

**Comment by hiddeco** [comment]
This is indirectly related to https://github.com/getsops/community/issues/9

**Comment by felixfontein** [comment]
@chrisgilmerproj do you have a link to that issue? This is quite a problem for many other projects as well (quite a few changelogs for Ansible-related projects use RST and also no longer render on GitHub).

**Comment by felixfontein** [comment]
I found https://github.com/orgs/community/discussions/86715 so far, but that only shows others are having this problem too.

**Comment by chrisgilmerproj** [comment]
@felixfontein - Here's what I got from Github support before they closed my ticket:

> Thank you for writing in! I'm sorry you have experienced this problem.
>
> I’ve escalated your report to our engineering team for further investigation.
>
> I'm afraid our system may mark this ticket as "solved" now that the issue has been created with the engineering team, but that doesn't mean we've forgotten about it.
>
> We'll be back in touch when we have any updates!
>
> If there is anything else I can help you with, please let me know 😁

I have left a request for them to link me to the engineering ticket so that I might connect you to it. 

Thanks again for looking into this.

**Comment by felixfontein** [comment]
@chrisgilmerproj thanks a lot! My guess is that they changed a timeout, or maybe they pre-rendered these documents in the past and stopped doing that... There has been no change to the renderer itself in the last months (or at least none to https://github.com/github/markup, which apparently contains the code).

**Comment by felixfontein** [comment]
As a temporary fix, we could programmatically convert the RST file to MD until all PRs modifying the RST have been merged and we decided how to continue with the README in general. I've created #1424 for this.

@getsops/maintainers what do you think?

**Comment by Gowiem** [comment]
@hiddeco are you the main maintainer nowadays? Anyway we can get the workaround PR merged to fix this issue? I am giving a talk on SOPS next week and this issue concerns me as folks are going to come to the project and think it's dead / not run currently, which makes my talk look bad haha. Please help out if you can!

**Comment by hiddeco** [comment]
The project is far from dead or unmaintained, and we have multiple people looking after it including plans in the works to ramp up the engagement with the community.

Due to some unfortunate events around the company that used to pay me for my work in open-source, in combination with COVID and some other family related matters, I have been distracted for the last month(s). But I have the following two weeks available to spend on going through the backlog.

**Comment by felixfontein** [comment]
The README is now rendering again - see https://github.com/orgs/community/discussions/86715#discussioncomment-8893219. Unfortunately the code blocks have no syntax highlighting, but instead have underlines. But hey, at least it's readable again... :shrug:

**Comment by felixfontein** [comment]
The broken RST code block syntax highlighting has a separate discussion on GitHub: https://github.com/orgs/community/discussions/113792

**Comment by felixfontein** [comment]
The table of contents is back as well. I think this is now (finally) resolved.

We're planning to move all documentation to a proper docsite anyway, so I'm going to close this. Thanks everyone!

**Comment by chrisgilmerproj** [comment]
Thanks for handling this! We appreciate it.
